
--  SECTION - A

-- 1.Write a query to list actors whose last name is 'ALLEN'.
select * 
from  actor 
where last_name ='ALLEN';

-- 2.Write a query to find the `first_name`, `last_name`, and `email` of all customers whose first name is 'JENNIFER'.
select first_name,last_name, email 
from customer
where first_name = 'JENNIFER';

-- 3.Write a query to list the `title`, `release_year`, and `rating` of all films that are rated 'PG-13'.
select title, release_year, rating
from film
where rating = 'PG-13';

-- 4. Write a query to display the `title` and `length` of all films, ordered from the longest film to the shortest.
select title, length
from film
order by length desc;

-- 5.  Write a query to show the `customer_id`, `amount`, and `payment_date` for the 10 most recent payments.
select customer_id ,amount, payment_date 
from payment
order by payment_date desc
limit 10;

-- --------------------------------------------------------------
-- SECTION - B

-- 1. Write a query to list the first name and last name of all actors who appeared in the film 'AGENT TRUMAN'.
select a.first_name, a.last_name
from actor a
join film f
on a.actor_id= f.film_id
where f.title ='AGENT TRUMAN';

-- 2. Write a query to display the first name, last name, address, and city for customer 'MARY SMITH'.
select ct.city,a.address,
       concat(c.first_name, ' ', c.last_name) AS customer_name
from customer c
join address a
  on c.address_id = a.address_id
join city ct
  on ct.city_id = a.city_id
where c.first_name = 'MARY'
  and c.last_name = 'SMITH';

-- 3.  Write a query to show the name of each category and the total number of films in that category.
select c.name,
count(f.film_id) as total_films
from category c
join film_category fc
on fc.category_id = c.category_id
join film f
on f.film_id = fc.film_id
group by c.name;

-- 4. Write a query to find the `title` and `description` of all films that have the word 'Drama' anywhere in their `description`.
select title,description
from film 
where description = 'drama';

-- 5. Write a query to find the `title` and `rental_duration` for all films that can be rented for more than 5 days.
select title,rental_duration
from film 
where rental_duration > 5;

-- 6. Write a query to list each `customer_id` and the total `amount` they have paid in rentals. Order the results by the total amount, from highest to lowest.
select customer_id, sum(amount)as total_amount
from payment
group by customer_id
order by total_amount Desc;

-- 7. Write a query to find the `first_name`, `last_name`, and `city` for all customers who live in 'Aurora' or 'London'.
select c.first_name, c.last_name ,ct. city
from customer c
join address a
on a.address_id = c.address_id
join city ct
on ct.city_id = a.city_id
where city = 'Aurora' or city = 'London';

-- 8. Write a query to find the average `rental_rate` for each film `rating` (G, PG, etc.).
select rating, avg(rental_rate)as avg_rate
from film
group by rating
order by avg_rate;

-- 9.  Write a query to find the `first_name` and `last_name` of actors who have appeared in more than 30 films. Also, show the count of films they appeared in.
select  a.first_name,a.last_name ,count(fa.film_id)as appeared_film
from actor a 
join film_actor fa
on fa. actor_id= a.actor_id
where a.actor_id >30
group by a.actor_id;

-- 10. Write a query to find all payments with an `amount` greater than 5.00 that were made between '2005-05-25' and '2005-05-30'.
select *
from payment 
where amount >5.00 and payment_date between '2005-05-25' and '2005-05-30';

-- 11. Write a query to display the `title` and `description` of all films in the 'Action' category. 
-- Use a subquery to find the `category_id` for 'Action'.
select title,description
from film 
where film_id = (Select category_id
from category 
where name = 'Action');

-- 12.Write a query to list the `first_name` and `last_name` of all customers who have rented the film 'AFRICAN EGG'.
select c.first_name, c.last_name
from customer c
join  inventory i
on i.store_id = c.store_id
join film f
on f.film_id = i.film_id
where title = 'AFRICAN EGG';

-- 13. Write a query to find all film titles that do *not* have any copies in the `inventory`.
select title from film
where film_id not in ( select distinct film_id from inventory);

-- 14. Write a query to show the `store_id` and the total revenue (sum of `amount` from the `payment` table) generated by each store.
select s.store_id, sum(p.amount)as t_rev
from store s 
join staff st 
on s.store_id=st.store_id
join payment p 
on p.staff_id=st.staff_id
group by s.store_id;

-- 15. Write a query to find the `first_name` and `last_name` of the customer who has spent the most money.
SELECT c.first_name, c.last_name
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id , c.first_name , c.last_name
ORDER BY SUM(p.amount) DESC
LIMIT 1;